### PR TITLE
Added isObject to SealedTrait.Subtype

### LINKED ISSUE #164: isObject for subtypes in dispatch
Would be very useful if we could find out if a subtype is an object when using subtypes in dispatch.

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #164

This adds `isObject` as a parameter to `Subtype`.

One thing I was not sure on, is why the fallback implicit is required in traits used for testing (I see TypeNameInfo has it). This is only required for sealed traits which have a mixture of case classes and case objects.

### CODE REVIEW

**Review by KacperFKorban — APPROVED** [review]
LGTM

**Comment by adamw** [comment]
Thanks!

**Comment by sksamuel** [comment]
Cool. Is there an auto snapshot ?

**Comment by adamw** [comment]
Snapshot - no, but there's a release being built: https://github.com/softwaremill/magnolia/actions/runs/922133541

**Comment by sksamuel** [comment]
Even better :)

**Pull request merged**
