### PR TITLE
Added annotations to sealed trait and sealed trait subtypes

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Review by KacperFKorban — APPROVED** [review]
Looks great!

**Comment by sksamuel** [comment]
Cool :)

**Comment by sksamuel** [comment]
Can you do a snapshot? I'm using this to upgrade https://github.com/sksamuel/avro4s

**Comment by KacperFKorban** [comment]
Created `2.0.0-M7`

**Comment by sksamuel** [comment]
Awesome :)

**Pull request merged**
